-- Word bank schema for idioms and life words
create table if not exists word_bank (
  id bigint generated by default as identity primary key,
  word_id bigint unique not null,
  word text not null,
  category text not null,
  created_at timestamptz default now()
);

create index if not exists idx_word_bank_category on word_bank (category);
